//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Circus
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report1
    {
        public int ID { get; set; }
        public Nullable<decimal> Profit { get; set; }
        public Nullable<decimal> Expenses { get; set; }
        public string ID_Type { get; set; }
        public Nullable<int> ID_Month { get; set; }
        public Nullable<int> Year { get; set; }
    
        public virtual Month Month { get; set; }
    }
}
